/** UI 문자열 (ko / en / ja) — data-i18n 키와 t() 키에 사용 */

const COMMON_KO = {
  opt: { atk: '공', spd: '속', crit: '크', def: '방', hp: '체' },
  grade: { 0: '흰', 1: '초', 2: '파', 3: '보', 4: '황' },
  delete: '삭제',
  calculating: '계산 중...',
  resultPlaceholder: '결과가 여기에 표시됩니다',
};

const COMMON_EN = {
  opt: { atk: 'ATK', spd: 'SPD', crit: 'CRT', def: 'DEF', hp: 'HP' },
  grade: { 0: 'White', 1: 'Green', 2: 'Blue', 3: 'Purple', 4: 'Yellow' },
  delete: 'Remove',
  calculating: 'Calculating...',
  resultPlaceholder: 'Results will appear here',
};

const COMMON_JA = {
  opt: { atk: '攻', spd: '速', crit: '暴', def: '防', hp: '体' },
  grade: { 0: '白', 1: '緑', 2: '青', 3: '紫', 4: '黄' },
  delete: '削除',
  calculating: '計算中...',
  resultPlaceholder: '結果はここに表示されます',
};

function pack(common, rest) {
  return { common, ...rest };
}

export const MESSAGES = {
  ko: pack(COMMON_KO, {
    meta: { title: '텍스트배틀 팬사이트' },
    nav: {
      menuAria: '메뉴',
      home: '홈',
      probability: '카드 성장 계산기',
      ani: '애니 강화 시뮬레이터',
      efficiency: '효율 계산기',
      speed: '선공 계산기',
      attr: '속성 계산기',
      position: '포지션 성향 테스트',
      cardSim: '카드 시뮬레이터',
      characters: '개발자 캐릭터 소개',
    },
    home: {
      welcome: '텍스트배틀 팬사이트에 오신 것을 환영합니다!',
      playLine:
        '텍스트배틀 플레이 하러 가기 : <a href="https://battle.logbrix.ai">https://battle.logbrix.ai</a>',
      whatTitle: '텍스트배틀이란?',
      what1: '나만의 아이디어로 ai가 캐릭터를 만든다!',
      what2: '내가 만든 캐릭터로 다른 캐릭터와 전투하는 AI 멀티 모달 캐릭터 PVP RPG 게임!',
      what3: '지원 전투 : 1vs1, 3vs3, 보스전, 서버 통합 레이드',
      featuresTitle: '텍스트배틀 팬사이트 기능',
      featProb: '카드 성장 계산기 : 현재 부옵을 입력하면 이 카드가 목표 효율에 도달할 확률 계산',
      featAni: '애니 강화 시뮬레이터 : 일반 강화, 집중 강화로 30강 애니를 뽑는 시뮬레이터',
      featEff: '효율 계산기 : 카드 + 애니의 성능을 확인하는 지표인 효율을 계산',
      featSpeed: '선공 계산기 : 나와 상대 중 누가 선공인지 계산',
      featAttr: '속성 계산기 : 속성 상성에 따른 평타 데미지·체력 보정값 계산',
      featPos: '포지션 성향 테스트 : 나에게 딱 맞는 포지션 추천',
      featCard: '카드 시뮬레이터 : 5성 카드를 뽑는 시뮬레이터',
      featChar: '개발자 캐릭터 소개 : 컨늅 패밀리 소개☺️',
      noticeTitle: '안내',
      notice1: '@TeamGurod 해당 사이트는 TeamGurod, logbrix.Textbattle의 공식사이트가 아닙니다!',
      notice2: '모든 리소스는 게임 텍스트배틀을 제작한 TeamGurod에게 있습니다!',
      notice3: 'Artist : 컨늅',
    },
    efficiency: {
      title: '효율 계산기',
      atk: '공격',
      def: '방어',
      hp: '체력',
      resultLabel: '효율',
      f1: '효율 = 공×2 + 방×2 + 체',
      f2: '효율 80 ⬇️ 캐릭터의 기본 스펙이 낮습니다.',
      f3: '효율 81 ⬆️ ~ 100 ⬆️ 준수하지만 속공, 크리, 방부옵에 조금 많이 투자된 것 같습니다.',
      f4: '효율 101 ⬆️ ~ 120 ⬇️ 준수합니다.',
      f5: '효율 121 ⬆️ ~ 140 ⬇️ 꽤 높습니다.',
      f6: '효율 141 ⬆️ ~ 170 ⬇️ 깡스펙으로 이기는 판이 있을겁니다.',
      f7: '효율 171 ⬆️ 거진 신의 경지',
      f8: '포지션 별 효율 계산법은 차이가 있습니다.',
    },
    speed: {
      title: '선공 계산기',
      myAgi: '내 민첩성',
      mySpd: '내 속부옵',
      enemyAgi: '상대 민첩성',
      enemySpd: '상대 속부옵',
      conv: '속부옵 효율',
      footnote: '공격성에 포함된 민첩이나 레벨 보정은 계산하지 않습니다.',
      empty: '값을 입력하세요',
      tie: '당신과 상대의 민첩성이 동일합니다.',
      firstMe:
        '민첩성 기준으로 {totalDiff} 차이, 속부옵 기준으로 {spdOptionDiff}개 차이로 당신이 선공입니다!',
      firstEnemy:
        '민첩성 기준으로 {totalDiff} 차이, 속부옵 기준으로 {spdOptionDiff}개 차이로 상대가 선공입니다!',
    },
    attr: {
      title: '속성 계산기',
      intro:
        '나와 상대의 속성만 입력되어 있으면 계산할 수 있습니다. 체력·평타는 비워 둘 수 있으며, 결과에는 (작성하지 않음)으로 표시됩니다.',
      me: '나',
      opp: '상대',
      myAtk: '나의 평타 데미지',
      myHp: '나의 체력',
      myElem: '나의 속성',
      oppAtk: '상대의 평타 데미지',
      oppHp: '상대의 체력',
      oppElem: '상대의 속성',
      select: '선택',
      elem: {
        fire: '불',
        none: '무',
        mind: '정신',
        water: '물',
        thunder: '번개',
        wind: '바람',
        dark: '어둠',
        light: '빛',
        earth: '대지',
      },
      calc: '계산',
      resultPlaceholder: '결과가 여기에 표시됩니다',
      matrixTitle: '속성 상성표 (%)',
      matrixHint: '행: 보정을 받는 속성 · 열: 상대 속성 (동일 속성은 0%)',
      matrixCorner: '행 \\ 열',
      matrixDash: '—',
      errorSelect: '나와 상대의 속성을 모두 입력해주세요.',
      summaryPrefix: '속성 보정 ',
      summaryJoin: ' · ',
      youAdj: '나: ',
      oppAdj: '상대: ',
      stanceFallbackYou: '당신 쪽 상성 보정은 {pct}입니다.',
      stanceFallbackOpp: '상대 쪽 상성 보정은 {pct}입니다.',
      stance: {
        even: '당신은 경합입니다.',
        slightDis: '당신은 약열세입니다.',
        slightAdv: '상대는 약우세입니다.',
        dis: '당신은 열세입니다.',
        adv: '상대는 우세입니다.',
      },
      lineKeys: {
        myDmg: '나의 평타 데미지',
        myHp: '나의 체력',
        oppDmg: '상대의 평타 데미지',
        oppHp: '상대의 체력',
      },
      omitted: '(작성하지 않음)',
      afterSuffix: ' (보정 후)',
      arrow: ' → ',
    },
    probability: {
      title: '카드 성장 계산기',
      subListLabel: '현재 부옵 리스트',
      subHint: '부옵을 추가하세요 (최대 4개)',
      add: '추가',
      targetStar: '목표 성급',
      targetEff: '목표 효율',
      calcBtn: '계산하기',
      star2: '2성',
      star3: '3성',
      star4: '4성',
      star5: '5성',
      errTooMany: '부옵을 목표 성급과 같거나 높게 추가할 수 없습니다.',
      errNoSubs: '계산을 원하시는 카드의 부옵을 추가 해주세요',
      prob100: '목표 효율 {eff}의 달성 확률은 100% 입니다.',
      prob0: '목표 효율 {eff} 달성 확률: 0%',
      prob: '목표 효율 {eff} 달성 확률: {pct}%',
      calcErr: '계산 오류: ',
    },
    ani: {
      title: '애니 강화 시뮬레이터',
      mode: '강화 모드',
      modeNormal: '일반 강화 (집중 강화 없음)',
      modeFocus: '집중 강화 (선택한 옵션 강화 확률 40%)',
      focusOpt: '집중 강화 옵션',
      pickaxe: '곡괭이 On/Off (선택한 옵션이 강화되면 즉시 곡괭이 사용)',
      pickaxeOpts: '곡괭이 사용 옵션 (최대 3개)',
      run: '0강 → 30강 시뮬레이션',
      resTotal: '총 시도 횟수',
      resSuccess: '성공',
      resFail: '실패',
      resDown: '하락',
      resFocusOpt: '집중 강화 옵션',
      resFocusHits: '집중 강화 옵션 강화 횟수',
      timesUnit: '회',
      resPickOpts: '곡괭이 사용 옵션',
      resPickUses: '곡괭이 사용 횟수',
      none: '없음',
      slotSum: '({n}칸) 합계값: {v}',
      unitSlot: '칸',
    },
    position: {
      title: '포지션 성향 테스트',
      intro: '7개의 질문에 답하여 나에게 맞는 포지션을 알아보세요.',
      start: '테스트 시작',
      next: '다음 질문',
      showResult: '결과 보기',
      recTitle: '추천 포지션',
      cont: '테스트 계속하기',
      restart: '처음부터 다시',
    },
    card: {
      title: '카드 시뮬레이터',
      roll: '5성 카드 뽑기',
      foot: '타 유저분의 확률 통계표를 참고 했습니다.',
    },
    characters: {
      title: '개발자 캐릭터 소개',
      imgAlt: '캐릭터',
      randomArt: '일러스트 변경',
    },
    footer: { text: '@TeamGurod · 텍스트배틀 팬사이트 · 컨늅 제작' },
    menu: { b1: '으에에엥', b2: '우클릭 네르지 마세요!' },
    lang: { aria: '언어 선택' },
  }),

  en: pack(COMMON_EN, {
    meta: { title: 'Text Battle Fan Site' },
    nav: {
      menuAria: 'Menu',
      home: 'Home',
      probability: 'Card growth calculator',
      ani: 'Ani enhancement simulator',
      efficiency: 'Efficiency calculator',
      speed: 'First strike calculator',
      attr: 'Attribute calculator',
      position: 'Position quiz',
      cardSim: 'Card simulator',
      characters: 'Dev characters',
    },
    home: {
      welcome: 'Welcome to the Text Battle fan site!',
      playLine:
        'Play Text Battle: <a href="https://battle.logbrix.ai">https://battle.logbrix.ai</a>',
      whatTitle: 'What is Text Battle?',
      what1: 'Use your ideas and let AI build your character!',
      what2: 'An AI multimodal character PVP RPG where your creations fight others!',
      what3: 'Modes: 1v1, 3v3, boss raids, server-wide raids',
      featuresTitle: 'What you can do here',
      featProb: 'Card growth calculator: enter substats to estimate odds of hitting target efficiency',
      featAni: 'Ani simulator: normal or focused enhancement to +30',
      featEff: 'Efficiency calculator: the stat index for card + Ani performance',
      featSpeed: 'First strike calculator: who moves first',
      featAttr: 'Attribute calculator: normal-attack damage and HP modifiers from matchups',
      featPos: 'Position quiz: find a role that fits you',
      featCard: 'Card simulator: roll a 5★ card',
      featChar: 'Dev characters: meet the Coneip family ☺️',
      noticeTitle: 'Notice',
      notice1: '@TeamGurod This site is not an official TeamGurod or logbrix.Textbattle website.',
      notice2: 'All game assets belong to TeamGurod, makers of Text Battle.',
      notice3: 'Artist: Coneip',
    },
    efficiency: {
      title: 'Efficiency calculator',
      atk: 'Attack',
      def: 'Defense',
      hp: 'HP',
      resultLabel: 'Efficiency',
      f1: 'Efficiency = ATK×2 + DEF×2 + HP',
      f2: '≤80: baseline stats are low.',
      f3: '81–100: decent, likely invested in SPD/CRT/DEF substats.',
      f4: '101–120: solid.',
      f5: '121–140: quite high.',
      f6: '141–170: raw stats can carry fights.',
      f7: '171+: nearly divine territory.',
      f8: 'Efficiency formulas differ by position.',
    },
    speed: {
      title: 'First strike calculator',
      myAgi: 'My agility',
      mySpd: 'My SPD substat',
      enemyAgi: 'Enemy agility',
      enemySpd: 'Enemy SPD substat',
      conv: 'SPD substat conversion',
      footnote: 'Agility from attack stance or level scaling is not included.',
      empty: 'Enter values',
      tie: 'You and the enemy have the same agility.',
      firstMe:
        'By agility the gap is {totalDiff}; in SPD substat steps (~{spdOptionDiff}) you take first strike!',
      firstEnemy:
        'By agility the gap is {totalDiff}; in SPD substat steps (~{spdOptionDiff}) the enemy takes first strike!',
    },
    attr: {
      title: 'Attribute calculator',
      intro:
        'Attributes for both sides are required. HP and normal-attack damage may be left blank; those lines show as “not entered.”',
      me: 'You',
      opp: 'Enemy',
      myAtk: 'My normal-attack damage',
      myHp: 'My HP',
      myElem: 'My element',
      oppAtk: 'Enemy normal-attack damage',
      oppHp: 'Enemy HP',
      oppElem: 'Enemy element',
      select: 'Select',
      elem: {
        fire: 'Fire',
        none: 'Neutral',
        mind: 'Mind',
        water: 'Water',
        thunder: 'Thunder',
        wind: 'Wind',
        dark: 'Dark',
        light: 'Light',
        earth: 'Earth',
      },
      calc: 'Calculate',
      resultPlaceholder: 'Results appear here',
      matrixTitle: 'Element matchup table (%)',
      matrixHint: 'Row: element receiving the modifier · Column: enemy element (same element = 0%)',
      matrixCorner: 'Row \\ Col',
      matrixDash: '—',
      errorSelect: 'Please choose both elements.',
      summaryPrefix: 'Element modifiers ',
      summaryJoin: ' · ',
      youAdj: 'You: ',
      oppAdj: 'Enemy: ',
      stanceFallbackYou: 'Your matchup modifier is {pct}.',
      stanceFallbackOpp: 'The enemy’s matchup modifier is {pct}.',
      stance: {
        even: 'You are even.',
        slightDis: 'You are slightly disadvantaged.',
        slightAdv: 'The enemy is slightly advantaged.',
        dis: 'You are disadvantaged.',
        adv: 'The enemy is advantaged.',
      },
      lineKeys: {
        myDmg: 'My normal-attack damage',
        myHp: 'My HP',
        oppDmg: 'Enemy normal-attack damage',
        oppHp: 'Enemy HP',
      },
      omitted: '(not entered)',
      afterSuffix: ' (after modifier)',
      arrow: ' → ',
    },
    probability: {
      title: 'Card growth calculator',
      subListLabel: 'Current substats',
      subHint: 'Add substats (max 4)',
      add: 'Add',
      targetStar: 'Target rarity',
      targetEff: 'Target efficiency',
      calcBtn: 'Calculate',
      star2: '2★',
      star3: '3★',
      star4: '4★',
      star5: '5★',
      errTooMany: 'You cannot add more substats than the target rarity allows.',
      errNoSubs: 'Add at least one substat to calculate.',
      prob100: 'Chance to reach efficiency {eff}: 100%.',
      prob0: 'Chance to reach efficiency {eff}: 0%',
      prob: 'Chance to reach efficiency {eff}: {pct}%',
      calcErr: 'Error: ',
    },
    ani: {
      title: 'Ani enhancement simulator',
      mode: 'Mode',
      modeNormal: 'Normal (no focus enhancement)',
      modeFocus: 'Focus (+40% chance on chosen stat)',
      focusOpt: 'Focused stat',
      pickaxe: 'Pickaxe on/off (use pickaxe immediately when a chosen stat upgrades)',
      pickaxeOpts: 'Pickaxe triggers (max 3)',
      run: 'Simulate +0 → +30',
      resTotal: 'Total attempts',
      resSuccess: 'Successes',
      resFail: 'Failures',
      resDown: 'Downgrades',
      resFocusOpt: 'Focused stat',
      resFocusHits: 'Focus hits',
      timesUnit: '',
      resPickOpts: 'Pickaxe trigger stats',
      resPickUses: 'Pickaxe uses',
      none: 'None',
      slotSum: '({n} slots) total: {v}',
      unitSlot: 'slots',
    },
    position: {
      title: 'Position tendency quiz',
      intro: 'Answer seven questions to see which position fits you.',
      start: 'Start',
      next: 'Next',
      showResult: 'See result',
      recTitle: 'Suggested position',
      cont: 'Continue quiz',
      restart: 'Start over',
    },
    card: {
      title: 'Card simulator',
      roll: 'Roll a 5★ card',
      foot: 'Rates reference community-collected statistics.',
    },
    characters: {
      title: 'Developer characters',
      imgAlt: 'Character',
      randomArt: 'Change illustration',
    },
    footer: { text: '@TeamGurod · Text Battle fan site · by Coneip' },
    menu: { b1: 'Uwaaa', b2: 'Please do not right-click!' },
    lang: { aria: 'Language' },
  }),

  ja: pack(COMMON_JA, {
    meta: { title: 'テキストバトル ファンサイト' },
    nav: {
      menuAria: 'メニュー',
      home: 'ホーム',
      probability: 'カード成長計算機',
      ani: 'アニ強化シミュ',
      efficiency: '効率計算機',
      speed: '先手計算機',
      attr: '属性計算機',
      position: 'ポジション診断',
      cardSim: 'カードシミュ',
      characters: '開発者キャラ紹介',
    },
    home: {
      welcome: 'テキストバトル ファンサイトへようこそ！',
      playLine:
        'プレイはこちら：<a href="https://battle.logbrix.ai">https://battle.logbrix.ai</a>',
      whatTitle: 'テキストバトルとは？',
      what1: '自分のアイデアでAIがキャラを生成！',
      what2: '作ったキャラで戦うAIマルチモーダルキャラPVP RPG！',
      what3: '対応：1vs1、3vs3、ボス戦、サーバー統合レイド',
      featuresTitle: 'このサイトの機能',
      featProb: 'カード成長計算機：現在のサブを入れると目標効率到達確率を計算',
      featAni: 'アニ強化シミュ：通常／集中強化で+30アニをシミュ',
      featEff: '効率計算機：カード+アニの指標「効率」を計算',
      featSpeed: '先手計算機：自分と相手のどちらが先手か',
      featAttr: '属性計算機：相性による通常ダメージ・HP補正',
      featPos: 'ポジション診断：あなたに合うポジを提案',
      featCard: 'カードシミュ：★5カードを引く',
      featChar: '開発者キャラ紹介：コニープファミリー紹介☺️',
      noticeTitle: '注意',
      notice1: '@TeamGurod 本サイトはTeamGurodおよびlogbrix.Textbattleの公式ではありません。',
      notice2: 'ゲーム資産はText Battle制作TeamGurodに帰属します。',
      notice3: 'Artist：コニープ',
    },
    efficiency: {
      title: '効率計算機',
      atk: '攻撃',
      def: '防御',
      hp: '体力',
      resultLabel: '効率',
      f1: '効率 = 攻×2 + 防×2 + 体',
      f2: '効率80以下：基礎ステが低め。',
      f3: '81〜100：そこそこ。速度・会心・防サブに寄せている可能性。',
      f4: '101〜120：及第。',
      f5: '121〜140：かなり高い。',
      f6: '141〜170：ステ量で押せる局面も。',
      f7: '171以上：ほぼ神域。',
      f8: 'ポジションごとに効率の計算式は異なります。',
    },
    speed: {
      title: '先手計算機',
      myAgi: '自分の敏捷',
      mySpd: '自分の速サブ',
      enemyAgi: '相手の敏捷',
      enemySpd: '相手の速サブ',
      conv: '速サブ換算',
      footnote: '攻撃性に含まれる敏捷やレベル補正は含みません。',
      empty: '値を入力してください',
      tie: '自分と相手の敏捷が同じです。',
      firstMe:
        '敏捷差 {totalDiff}、速サブ換算で約 {spdOptionDiff} 本分の差で、あなたが先手です！',
      firstEnemy:
        '敏捷差 {totalDiff}、速サブ換算で約 {spdOptionDiff} 本分の差で、相手が先手です！',
    },
    attr: {
      title: '属性計算機',
      intro:
        'お互いの属性があれば計算できます。体力・通常ダメージは空欄可。未入力は（未入力）と表示されます。',
      me: '自分',
      opp: '相手',
      myAtk: '自分の通常ダメージ',
      myHp: '自分の体力',
      myElem: '自分の属性',
      oppAtk: '相手の通常ダメージ',
      oppHp: '相手の体力',
      oppElem: '相手の属性',
      select: '選択',
      elem: {
        fire: '火',
        none: '無',
        mind: '精神',
        water: '水',
        thunder: '雷',
        wind: '風',
        dark: '闇',
        light: '光',
        earth: '大地',
      },
      calc: '計算',
      resultPlaceholder: '結果はここに表示されます',
      matrixTitle: '属性相性表 (%)',
      matrixHint: '行：補正を受ける属性／列：相手属性（同属性は0%）',
      matrixCorner: '行＼列',
      matrixDash: '—',
      errorSelect: '自分と相手の属性を両方選んでください。',
      summaryPrefix: '属性補正 ',
      summaryJoin: ' · ',
      youAdj: '自分: ',
      oppAdj: '相手: ',
      stanceFallbackYou: 'あなた側の相性補正は{pct}です。',
      stanceFallbackOpp: '相手側の相性補正は{pct}です。',
      stance: {
        even: 'あなたは互角です。',
        slightDis: 'あなたはやや不利です。',
        slightAdv: '相手はやや有利です。',
        dis: 'あなたは不利です。',
        adv: '相手は有利です。',
      },
      lineKeys: {
        myDmg: '自分の通常ダメージ',
        myHp: '自分の体力',
        oppDmg: '相手の通常ダメージ',
        oppHp: '相手の体力',
      },
      omitted: '（未入力）',
      afterSuffix: '（補正後）',
      arrow: ' → ',
    },
    probability: {
      title: 'カード成長計算機',
      subListLabel: '現在のサブ一覧',
      subHint: 'サブを追加（最大4）',
      add: '追加',
      targetStar: '目標レア',
      targetEff: '目標効率',
      calcBtn: '計算',
      star2: '★2',
      star3: '★3',
      star4: '★4',
      star5: '★5',
      errTooMany: '目標レア以上の数のサブは追加できません。',
      errNoSubs: '計算したいカードのサブを追加してください',
      prob100: '目標効率 {eff} 到達確率：100%です。',
      prob0: '目標効率 {eff} 到達確率：0%',
      prob: '目標効率 {eff} 到達確率：{pct}%',
      calcErr: '計算エラー: ',
    },
    ani: {
      title: 'アニ強化シミュレータ',
      mode: '強化モード',
      modeNormal: '通常強化（集中なし）',
      modeFocus: '集中強化（選択オプ強化確率40%）',
      focusOpt: '集中強化オプション',
      pickaxe: 'ツルハシ On/Off（選択オプが強化されたら即使用）',
      pickaxeOpts: 'ツルハシ対象オプ（最大3）',
      run: '+0→+30 シミュレーション',
      resTotal: '総試行回数',
      resSuccess: '成功',
      resFail: '失敗',
      resDown: '下降',
      resFocusOpt: '集中強化オプション',
      resFocusHits: '集中ヒット回数',
      timesUnit: '回',
      resPickOpts: 'ツルハシ対象',
      resPickUses: 'ツルハシ使用回数',
      none: 'なし',
      slotSum: '（{n}マス）合計: {v}',
      unitSlot: 'マス',
    },
    position: {
      title: 'ポジション傾向テスト',
      intro: '7問に答えてあなたに合うポジションを探しましょう。',
      start: 'テスト開始',
      next: '次の質問',
      showResult: '結果を見る',
      recTitle: 'おすすめポジション',
      cont: '続ける',
      restart: '最初から',
    },
    card: {
      title: 'カードシミュレータ',
      roll: '★5カードを引く',
      foot: '他プレイヤー集計の確率表を参考にしています。',
    },
    characters: {
      title: '開発者キャラ紹介',
      imgAlt: 'キャラクター',
      randomArt: 'イラスト変更',
    },
    footer: { text: '@TeamGurod · テキストバトル ファンサイト · コニープ作' },
    menu: { b1: 'うぇええん', b2: '右クリックはやめてね！' },
    lang: { aria: '言語' },
  }),
};
